### ISSUE TITLE
Could not stream mp3 with libshout 2.4.5

### ISSUE THREAD

**Issue by zygmund2000** [xiph/ezstream#30]
Hi,

I have some problem to stream mp3:

ezstream[19314]: stream: default: format: MP3: This libshout doesn't support the requested option

I have libshout 2.4.5

**Comment by fungi** [comment]
I encountered the same issue recently on a Debian/Sid machine after upgrading to ezstream 1.0.2 built against libshout3 2.4.5, and while switching the stream to Ogg worked around it, that resulted in some fairly terrible stream discontinuities. Downgrading to ezstream 1.0.1 with libshout3 2.4.4 restored things to working order with my original MP3 stream configuration..

**Comment by soika1978** [comment]
Just to note that ezstream 1.0.1 + libshout 2.4.4 also required explicit < tls >none< /tls > tag, since default value as "May" fails

**Comment by simon1tan** [comment]
There is a patch from a user here which worked for me
https://gitlab.xiph.org/xiph/ezstream/-/issues/2271

**Comment by codekandis** [comment]
That patch worked for me, too.

**Comment by ThatOneRuffian** [comment]
Thanks, the patch worked for me as well.

**Comment by alexdowad** [comment]
The patch worked for me too. I hope the maintainer will merge it into 'master' soon!

**Comment by newmediacrew** [comment]
Maybe a noob question, but how do you apply that patch via the terminal?

**Comment by ThatOneRuffian** [comment]
> Maybe a noob question, but how do you apply that patch via the terminal?

The "patch" is just a text file showing the changes needed in the source code to be able to stream an mp3. After manually changing these lines, you must then compile the code to produce the new binary. However, this requires a working development environment to be able to compile for this project which requires a fair bit of setup that can change depending on which OS you're using.

At this point, I'd just recommend using [liquidsoap](https://www.liquidsoap.info)

**Comment by mgrimm** [comment]
Thanks for the patience and the report ...

A fix is pushed to develop and will be part of the next release. Any help with testing is much appreciated.

**Comment by roughnecks** [comment]
I have the same issue on Debian 11, what's the current fix?

**Comment by alexdowad** [comment]
@roughnecks Did you try the patch which is linked above?

**Comment by roughnecks** [comment]
> @roughnecks Did you try the patch which is linked above?

Yeah, I did now.. thought it was fixed in development. Thanks

**Comment by erikreimann** [comment]
I still have this problem with Ubuntu 22.04 (they provide ezstream 1.02 and libshout 2.4.5). It there any way to fix this without the need to compile myself? 

PS:
I made it work now: I downloaded the older ezstream version 1.01 from here:
https://packages.ubuntu.com/focal/amd64/ezstream/download
Then I installed the file:
sudo dpkg -i ezstream_1.0.1-1_amd64.deb
Works very well now :-) Thank you Moritz for providing this!
PS2: I needed to put the package on hold so that it does not get overwritten with the next apt-get upgrade:
sudo apt-mark hold ezstream

**Comment by erikreimann** [comment]
I made it work now: I downloaded the older ezstream version 1.01 from here:
http://mirrors.kernel.org/ubuntu/pool/universe/e/ezstream/ezstream_1.0.1-1_amd64.deb
Then I installed the file:
sudo dpkg -i ezstream_1.0.1-1_amd64.deb
Works very well now :-) Thank you Mr. Grimm for providing this!

**Comment by vfetisov** [comment]
Many thanks, @erikreimann !
This works for me as well.

**Comment by erikreimann** [comment]
> Thanks for the patience and the report ...
> 
> A fix is pushed to develop and will be part of the next release. Any help with testing is much appreciated.

A new release with the fix would be greatly appreciated. Otherwise I will need to give http://www.liquidsoap.info a try
Thanks to @ThatOneRuffian for bringing this up

**Comment by johnsie** [comment]
On Ubuntu Jammy I'm still getting this issue with the ezstream from the default repos. The solution from [erikreimann](https://github.com/erikreimann) worked for me, but I had to do --fix-broken. I've detailed my full process below:   

If the borked version of eztream is already installed then remove it:
sudo apt-get --purge autoremove ezstream


Download the older ezstream version 1.01 from here:
https://packages.ubuntu.com/focal/amd64/ezstream/download

Install the file:
sudo dpkg -i ezstream_1.0.1-1_amd64.deb

Fix the broken dependencies:
sudo apt --fix-broken install

Force the application to stay at this version by putting a hold on it:
sudo apt-mark hold ezstream
